image: haje01/wzdat

env:
    - WZDAT_DIR=$(pwd) 
    - WZDAT_CFG=tests/ws_mysol/myprj/config.yml 

script:
    - pip install -e .
    - pip install pytest
    - python -m wzdat.jobs gen-dummydata
    - py.test
    - coveralls

