image: haje01/wzdat

env:
    - WZDAT_DIR=$(pwd) 
    - WZDAT_CFG=$WZDAT_DIR/tests/ws_mysol/myprj/config.yml 
    - WZDAT_HOST=localhost
    - WZDAT_SOL_DIR=$WZDAT_DIR/tests
    - WZDAT_SOL_PKG=ws_mysol

script:
    - redis-server /etc/redis/redis.conf
    - pip install -e .
    - pip install pytest pytest-cov
    - python -m wzdat.jobs gen-dummydata
    - tar xzvf tests/test-notebooks.tar.gz
    - py.test tests/ --cov wzdat --cov-report xml
    # - coveralls
