image: haje01/wzdat-dev
docker:
    net: host

env:
    - WZDAT_DIR=$(pwd) 
    - WZDAT_CFG=tests/ws_mysol/myprj/config.yml 
    - WZDAT_HOST=localhost
    - WZDAT_SOL_DIR=$WZDAT_DIR/tests
    - WZDAT_SOL_PKG=ws_mysol
    - DOCKER_HOST=0.0.0.0:4243

script:
    - pip install -e .
    - python -m wzdat.jobs gen-dummydata
    - docker ps
    - cd /var/cache/drone/src/github.com/haje01/wzdat/system; fab launch:myprj
    - sleep 15  # wait for initializing
    - cd /var/cache/drone/src/github.com/haje01/wzdat; py.test tests/ system/tests/ --cov wzdat --cov-report xml
    # - cd /var/cache/drone/src/github.com/haje01/wzdat; py.test tests/ --cov wzdat --cov-report xml
    - coveralls
    - cd /var/cache/drone/src/github.com/haje01/wzdat/system; fab rm:myprj

