image: haje01/wzdat

env:
    - WZDAT_DIR=$(pwd) 
    - WZDAT_CFG=tests/ws_mysol/myprj/config.yml 

script:
    - pip install pytest
    - python -m wzdat.jobs gen-dummydata
    - py.test --cov wzdat --cov-report xml tests/
