image: haje01/wzdat

env:
    - WZDAT_DIR=$(pwd) 
    - WZDAT_CFG=tests/ws_mysol/myprj/config.yml 
    - WZDAT_HOST=localhost

script:
    - pip install -e .
    - pip install pytest
    - python -m wzdat.jobs gen-dummydata
    - py.test --cov wzdat --cov-report xml
    - coveralls

